---
title: "R Notebook"
output: html_notebook
---

```{r libraries}
rm(list=ls())
library(ggplot2)
library(tidyr)
library(psych)
library(dplyr)
library(grf)
library(rpart)
library(glmnet)
library(splines)
library(lmtest)
library(sandwich)
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(fastDummies)
library(xtable)
library("gridExtra") 
```
```{r import csv}
setwd('~/Mirror/github/aICLR/')
ICLR_author_profiles = read.csv("./data/authors/df_author_profiles.csv")
ICLR_author_profiles = ICLR_author_profiles %>% mutate_all(na_if,"")

ICLR_submissions = read.csv("./data/submissions/df_submissions.csv")
ICLR_submissions = ICLR_submissions %>% mutate_all(na_if,"")

ICLR_all_notes = read.csv("./data/submissions/df_all_notes.csv")
ICLR_all_notes = ICLR_all_notes %>% mutate_all(na_if,"")

ICLR_rr_all_features = read.csv("./data/df_rr_all_features.csv")
ICLR_rr_all_features = ICLR_rr_all_features %>% mutate_all(na_if,"")
```
```{r describe RR}
ICLR_all_rr = ICLR_all_notes %>% filter (rr_flag ==1 )



ICLR_all_review = ICLR_rr_all_features %>% filter (!is.na(review))

ICLR_all_comment = ICLR_rr_all_features %>% filter (!is.na(comment))

ICLR_all_decision_1718 = ICLR_all_notes %>% filter(!is.na(decision))
ICLR_all_decision_19 = ICLR_all_notes %>% filter(meta_flag == 1)

ICLR_all_decision_1718 %>% group_by(year,decision) %>%
  dplyr::summarise(n = n())

ICLR_all_decision_19 %>% group_by(year,recommendation) %>%
  dplyr::summarise(n = n())

ICLR_all_comment %>% group_by(year) %>%
  dplyr::summarise(n = n()) 

ICLR_all_review %>% group_by(year) %>%
  dplyr::summarise(n = n()) 

```

```{r describe authors}

describe(ICLR_author_profiles[c('email','year','gender',"location","institution", "X2017_position", "X2018_position", "X2019_position" )])[c("n")]

```
```{r describe submissions}

describe(ICLR_submissions)#[c("n")]

```
```{r describe submissions by year}
ICLR_submissions %>% group_by(invitation) %>%
      dplyr::summarise(n = n()) %>%
      mutate(freq = round(n  / sum(n ), 3))
```




```{r plots gender}
df = ICLR_author_profiles %>% group_by(year,gender) %>%
      dplyr::summarise(n = n()) %>%
      mutate(freq = round(n  / sum(n ), 3))
  


graph2=ggplot(df, aes(x = year, y = n)) + 
  geom_line(aes(color = gender, linetype = gender)) + 
  #scale_color_manual(values = c("darkred", "steelblue",'green','purple')) +
  ggtitle("Number of Authors by Gender Identity from ICLR 2017 - 2019") +
  scale_x_discrete(limit = c(2017, 2018, 2019)) +
  geom_point()

graph1 = ggplot(df, aes(x = year, y = freq)) + 
  geom_line(aes(color = gender, linetype = gender)) + 
  #scale_color_manual(values = c("darkred", "steelblue",'green','purple')) +
  ggtitle("Percent of Authors by Gender Identity from ICLR 2017 - 2019")+
  scale_x_discrete(limit = c(2017, 2018, 2019)) + 
  geom_point()

graph2
graph1
```

```{r describe politiness}

#hist(ICLR_all_review$polite_pred_score)
#hist(ICLR_all_comment$polite_pred_score)

Review_politiness = ICLR_all_review %>% group_by(year) %>%
  dplyr::summarise(ave_polite = mean(polite_pred_score),sd_polite = sd(polite_pred_score))

Comment_politiness = ICLR_all_comment %>% group_by(year) %>%
  dplyr::summarise(ave_polite = mean(polite_pred_score),sd_polite = sd(polite_pred_score))


ggplot(Review_politiness, aes(x=year, y=ave_polite)) + geom_point() +
  geom_errorbar(aes(ymin=ave_polite-sd_polite, ymax=ave_polite+sd_polite), width=.2,
              position=position_dodge(0.05)) +
  scale_x_discrete(limit = c(2017, 2018, 2019)) +
  ylim(0,1) +
  geom_line() +
  ggtitle("Average Politiness Score of Review by Year")


ggplot(Comment_politiness, aes(x=year, y=ave_polite)) + geom_point() +
  geom_errorbar(aes(ymin=ave_polite-sd_polite, ymax=ave_polite+sd_polite), width=.2,
              position=position_dodge(0.05)) +
  scale_x_discrete(limit = c(2017, 2018, 2019)) +
  ylim(0,1) +
  geom_line() +
  ggtitle("Average Politiness Score of Comment by Year")
```


